name: 🪟 Assemble Windows
on:
  workflow_call:
    inputs:
      godot-kotlin-jvm-version:
        type: string
      godot-version:
        type: string

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows
  cancel-in-progress: true

jobs:
  create-windows-editor-zip:
    runs-on: ubuntu-20.04
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Create editor zip release
            target: release

          - name: Create editor zip debug
            target: debug
    steps:
      - name: Download ${{ matrix.target }} editor
        uses: actions/download-artifact@v3
        with:
          name: editor_${{ matrix.target }}_windows_x86_64
          path: godot-kotlin-jvm_editor_windows_${{ matrix.target }}_${{ inputs.godot-kotlin-jvm-version }}

      - name: Download ${{ matrix.target }} bootstrap jar
        uses: actions/download-artifact@v3
        with:
          name: jvm_godot-bootstrap_${{ matrix.target }}
          path: godot-kotlin-jvm_editor_windows_${{ matrix.target }}_${{ inputs.godot-kotlin-jvm-version }}

      - name: Create windows editor zip
        run: |
          zip godot-kotlin-jvm_editor_windows_${{ matrix.target }}_${{ inputs.godot-kotlin-jvm-version }}.zip godot-kotlin-jvm_editor_windows_${{ matrix.target }}_${{ inputs.godot-kotlin-jvm-version }}/*
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: godot-kotlin-jvm_editor_windows_${{ matrix.target }}_${{ inputs.godot-kotlin-jvm-version }}.zip
          path: godot-kotlin-jvm_editor_windows_${{ matrix.target }}_${{ inputs.godot-kotlin-jvm-version }}.zip