name: 🐧 Linux Builds
on:
  workflow_call:

# Global Settings
env:
  GODOT_VERSION: 4.2-stable
  SCONSFLAGS: verbose=yes warnings=extra werror=yes module_text_server_fb_enabled=yes

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-linux
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor release (target=editor)
            cache-name: linux-editor-release
            target: editor
            sconsflags: ''
            bin: "./bin/godot.linuxbsd.editor.x86_64"

          - name: Editor dev (target=editor, dev_build=yes, debug_symbols=true )
            cache-name: linux-editor-dev
            target: editor
            sconsflags: dev_build=yes debug_symbols=true
            bin: "./bin/godot.linuxbsd.editor.dev.x86_64"

          - name: Release template
            cache-name: linux-template_release
            target: template_release
            sconsflags: ''

          - name: Debug template
            cache-name: linux-template_debug
            target: template_debug
            sconsflags: ''

    steps:
      - name: Clone Godot Engine
        uses: actions/checkout@v2
        with:
          repository: godotengine/godot
          ref: ${{ env.GODOT_VERSION }}

      - name: Clone Godot JVM module.
        uses: actions/checkout@v2
        with:
          path: modules/kotlin_jvm

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          platform: linuxbsd
          target: ${{ matrix.target }}

      - name: Prepare artifact
        if: ${{ matrix.artifact }}
        run: |
          strip bin/godot.*
          chmod +x bin/godot.*

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        if: ${{ matrix.artifact }}
        with:
          name: ${{ matrix.cache-name }}
