name: PR Checks
on: [pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-runner
  cancel-in-progress: true

jobs:
  build-jvm:
    name: ☕ Build Jvm
    uses: ./.github/workflows/builds_jvm.yml
    with:
      godot-version: 4.2-stable
      jvm-version: 17

  build-android:
    name: 🤖 Build Android
    uses: ./.github/workflows/builds_android.yml
    with:
      godot-version: 4.2-stable
      jvm-version: 17

  build-ios:
    name: 🍏 Build iOS
    uses: ./.github/workflows/ios_builds.yml
    with:
      godot-version: 4.2-stable

  build-linux:
    name: 🐧 Build Linux
    uses: ./.github/workflows/builds_linux.yml
    with:
      godot-version: 4.2-stable

  build-macos:
    name: 🍎 Build macOS
    uses: ./.github/workflows/builds_macos.yml
    with:
      godot-version: 4.2-stable

  build-windows:
    name: 🪟 Build Windows
    uses: ./.github/workflows/builds_windows.yml
    with:
      godot-version: 4.2-stable

  test-linux:
    name: 🐧 Test Linux
    uses: ./.github/workflows/tests_linux.yml
    needs:
      - build-jvm
      - build-linux
    with:
      godot-version: 4.2-stable
      jvm-version: 17
