name: PR Checks
on: [pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-runner
  cancel-in-progress: true

jobs:
  jvm-build:
    name: ☕ Jvm
    uses: ./.github/workflows/builds_jvm.yml
    with:
      godot-version: 4.2-stable
      jvm-version: 17

  #  android-build:
#    name: 🤖 Android
#    uses: ./.github/workflows/android_builds.yml

#  ios-build:
#    name: 🍏 iOS
#    uses: ./.github/workflows/ios_builds.yml

  linux-build:
    name: 🐧 Linux
    uses: ./.github/workflows/builds_linux.yml
    with:
      godot-version: 4.2-stable

  macos-build:
    name: 🍎 macOS
    uses: ./.github/workflows/builds_macos.yml
    with:
      godot-version: 4.2-stable

  windows-build:
    name: 🪟 Windows
    uses: ./.github/workflows/builds_windows.yml
    with:
      godot-version: 4.2-stable
