name: PR Checks
on: [ pull_request ]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-runner
  cancel-in-progress: true

jobs:
  build-jvm:
    name: ☕ Build Jvm
    uses: ./.github/workflows/builds_jvm.yml
    with:
      godot-version: 4.2-stable
      jvm-version: 17

  build-android:
    name: 🤖 Build Android
    uses: ./.github/workflows/builds_android.yml
    with:
      godot-version: 4.2-stable
      jvm-version: 17

  build-ios:
    name: 🍏 Build iOS
    uses: ./.github/workflows/builds_ios.yml
    with:
      godot-version: 4.2-stable

  build-linux:
    name: 🐧 Build Linux
    uses: ./.github/workflows/builds_linux.yml
    with:
      godot-version: 4.2-stable

  build-macos:
    name: 🍎 Build macOS
    uses: ./.github/workflows/builds_macos.yml
    with:
      godot-version: 4.2-stable

  build-windows:
    name: 🪟 Build Windows
    uses: ./.github/workflows/builds_windows.yml
    with:
      godot-version: 4.2-stable

  assemble-macos:
    name: 🍎 Assemble macos
    uses: ./.github/workflows/assemble_macos.yml
    needs:
      - build-jvm
      - build-macos
    with:
      godot-kotlin-jvm-version: 0.8.1-4.2.0
      godot-version: 4.2-stable

  assemble-linux:
    name: 🍎 Assemble linux
    uses: ./.github/workflows/assemble_linux.yml
    needs:
      - build-jvm
      - build-linux
    with:
      godot-kotlin-jvm-version: 0.8.1-4.2.0
      godot-version: 4.2-stable

  assemble-windows:
    name: 🪟 Assemble windows
    uses: ./.github/workflows/assemble_windows.yml
    needs:
      - build-jvm
      - build-windows
    with:
      godot-kotlin-jvm-version: 0.8.1-4.2.0
      godot-version: 4.2-stable

  test-linux:
    name: 🐧 Test Linux
    uses: ./.github/workflows/tests_linux.yml
    needs:
      - build-jvm
      - build-linux
    with:
      godot-version: 4.2-stable
      jvm-version: 17
